play:
  name: Play
  description: Start playing the Gensokyo Radio stream on the configured target speaker.
  fields:
    entity_id:
      name: Entity
      description: The Gensokyo Radio media player entity.
      required: true
      selector:
        entity:
          integration: gensokyo_radio
          domain: media_player

stop:
  name: Stop
  description: Stop playback on the configured target speaker.
  fields:
    entity_id:
      name: Entity
      description: The Gensokyo Radio media player entity.
      required: true
      selector:
        entity:
          integration: gensokyo_radio
          domain: media_player
